version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: sunday
    time: "10:00"
    timezone: Europe/Berlin
  ignore:
  - dependency-name: gatsby-plugin-image
    versions:
    - 1.1.2
    - 1.2.0
    - 1.2.1
  - dependency-name: gatsby-plugin-sharp
    versions:
    - 3.1.2
    - 3.2.0
    - 3.2.1
  - dependency-name: gatsby-remark-images
    versions:
    - 4.1.1
    - 4.2.0
  - dependency-name: gatsby
    versions:
    - 3.1.2
    - 3.2.1
  - dependency-name: prismjs
    versions:
    - 1.21.0
    - 1.23.0
  - dependency-name: gatsby-transformer-remark
    versions:
    - 2.15.0
    - 2.16.0
    - 2.16.1
  - dependency-name: gatsby-remark-copy-linked-files
    versions:
    - 2.10.0
    - 2.9.0
  - dependency-name: gatsby-remark-responsive-iframe
    versions:
    - 2.10.0
    - 2.11.0
  - dependency-name: gatsby-plugin-manifest
    versions:
    - 2.6.1
  - dependency-name: bl
    versions:
    - 1.2.3
  - dependency-name: lodash
    versions:
    - 4.17.20
    - 4.17.21
  - dependency-name: socket.io
    versions:
    - 2.4.1
  - dependency-name: firebase-tools
    versions:
    - 9.2.2
    - 9.3.0
    - 9.4.0
  - dependency-name: elliptic
    versions:
    - 6.5.3
    - 6.5.4
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: graphql-playground-html
    versions:
    - 1.6.29
  - dependency-name: object-path
    versions:
    - 0.11.5
  - dependency-name: http-proxy
    versions:
    - 1.18.1
  - dependency-name: dot-prop
    versions:
    - 4.2.1
  - dependency-name: websocket-extensions
    versions:
    - 0.1.4
