# CircleCI Firebase Deployment Config
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/ashishsantikari.info
    steps:
      - checkout
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json
            - v1-npm-deps-{{ checksum "yarn.lock" }}
            # Fallback cache to be used
            - v1-npm-deps-
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: v1-npm-deps-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Gatsby Build
          command: npm run build
      - persist_to_workspace:
          root: ~/ashishsantikari.info
          paths:
            - build
            - firebase.json
  deploy:
    docker:
      - image: zeroplusx/firebase-tools
    working_directory: ~/ashishsantikari.info
    steps:
      - attach_workspace:
          at: ~/ashishsantikari.info
      - run:
          name: list workdir
          command: ls -l
      - run:
          name: Compress Artifacts
          command: tar -cvf build.tar public
      - run:
          name: List files
          command: ls -laf
      - store_artifacts:
          path: ./build.tar
      - persist_to_workspace:
          root: ~/ashishsantikari.info
          paths:
            - public
            - firebase.json
            - .firebaserc
  deploy:
    docker:
      - image: zeroplusx/firebase-tools
    working_directory: ~/ashishsantikari.info
    steps:
      - attach_workspace:
          at: ~/ashishsantikari.info
      - run:
          name: list workdir
          command: ls -l
      - run:
          name: Firebase Deploy
          command: firebase deploy --token "$FIREBASE_TOKEN"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build

